import "@/app/globals.css";
import { Inter, Lato, Playfair_Display } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const pfdisplay = Playfair_Display({
	subsets: ["latin", "vietnamese"],
	display: "swap",
	variable: "--font-playfair-display",
});
const lato = Lato({
	weight: ["700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-lato",
});

export const metadata = {
	title: `RUVSA | VCDC`,
	description: "Generated by create next app",
};

export default function VCDCLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<section
			className={`${inter.variable} ${pfdisplay.variable} ${lato.variable}`}
		>
			{children}
		</section>
	);
}
